configurations:
  - sources:
      - Sources/MockDeclarations/
    templates:
      - Sources/Templates/AutoMockable.swifttemplate
    output: Tests/TemplateTests
    args:
      imports: [Foundation, XCTest]
      testableImports: [MockDeclarations]
  - sources:
      - Sources/MockDeclarations/
    templates:
      - Sources/Templates/AutoStubbable.swifttemplate
    output: Tests/TemplateTests
    args:
      imports: [Foundation]
      testableImports: [MockDeclarations]
appel appel